name: regal-sea-goddess
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas==1.0.1
  - h5netcdf==1.6.4
  - ipykernel==6.25.2
  - fiona==1.10.1
  - matplotlib==3.7.0
  - netCDF4==1.7.2
  - numpy==1.23.2
  - optuna==4.5.0
  - pandas==2.3.2
  - pip==22.2.1
  - plotly==6.3.0
  - python==3.10.18
  - python-box==6.0.2
  - scipy==1.10.0
  - scikit-learn==1.0.2
  - streamlit==1.49.1
  - tqdm==4.64.0
  - xarray==2024.7.0
  - xgboost==2.1.4
